#! /bin/bash

## Updates the OpenJML update site at 
## https://sourceforge.net/projects/jmlspecs/files/OpenJML/updatesite
## which is being deprecated

cd C:/cygwin/home/dcok/eprojects/OpenJMLUpdateSite
rm -f web/*.gz
file=`ls -t ../OpenJML/*.tar.gz | head -1`
echo $file
cp ../OpenJML/$file web
sftp davidcok,jmlspecs@web.sourceforge.net  << HERE
cd /home/frs/project/j/jm/jmlspecs/OpenJML
put web/*.gz openjml.tar.gz
exit
HERE


