#! /bin/bash

## Updates the OpenJML update site at 
## https://sourceforge.net/projects/jmlspecs/files/OpenJML/updatesite
## which is being deprecated

cd C:/cygwin/home/dcok/eprojects/OpenJMLUpdateSite
cp ../../texstuff/papers/OpenJMLUserGuide/OpenJMLUserGuide.pdf web
rm -f web/*.gz
file=`ls -t ../OpenJML/*.tar.gz | head -1`
echo $file
cp ../OpenJML/$file web
sftp davidcok,jmlspecs@web.sourceforge.net  << HERE
cd /home/frs/project/j/jm/jmlspecs/OpenJML
put web/index.html
put web/book.css
put web/OpenJMLUserGuide.pdf
put web/*.gz openjml.tar.gz
cd updatesite
put web/openjml-updatesite/index.html
put web/book.css
put site.xml
put content.jar
put artifacts.jar
cd features
put features/*
cd ../plugins
put plugins/*
exit
HERE


