#! /bin/bash

## This updates http://jmlspecs.sourceforge.net/
## just the web pages, not the actual release files on the Eclipse update site

cd `dirname $BASH_SOURCE`
cd ..

source web/setup

if [ -z "$SFUSERNAME" ] ; then

export SFUSERNAME=$USER

fi

cat - | sftp $SFUSERNAME,jmlspecs@web.sourceforge.net 


