#! /bin/bash

## This updates http://jmlspecs.sourceforge.net/
## just the web pages, not the actual release files on the Eclipse update site

cd C:/cygwin/home/dcok/eprojects/OpenJML-UpdateSite
source web/setup

sftp davidcok,jmlspecs@web.sourceforge.net  << HERE
cd htdocs
put web/index.html
put web/installation.html
put web/features.html
put web/book.css
put web/OpenJML-projectSet.psf
put web/svn_commands
put web/OpenJMLUserGuide.pdf
cd openjml-updatesite
put web/openjml-updatesite/index.html
put web/book.css
exit
HERE


