#! /bin/bash

## This updates http://jmlspecs.sourceforge.net/
## and the associated update site with new files,
## but only uploading the most recent feature and plugins

cd `dirname $BASH_SOURCE`

cat projectfiles | publish



