#! /bin/bash

## This updates http://jmlspecs.sourceforge.net/
## just the web pages, not the actual release files on the Eclipse update site

cd `dirname $BASH_SOURCE`
cd ..

source web/setup

if [ -z "$SOURCEFORGE_USERNAME" ] ; then

export SOURCEFORGE_USERNAME=$USER

fi

echo "Using sourceforge user name $SOURCEFORGE_USERNAME"
echo "Version ${version}"
cat - | sed -e s/\$\{version\}/$version/ | sftp $SOURCEFORGE_USERNAME,jmlspecs@web.sourceforge.net 

echo "Upload Complete"
