#! /bin/bash

rm -rf temp-test
mkdir temp-test
cd temp-test
echo "Downloading release from sourceforge - takes a few minutes"
curl -s http://jmlspecs.sourceforge.net/openjml.zip -o openjml.zip
if [ $? -eq 0 ]; then 
  echo "Release downloaded"
  unzip -q openjml.zip
  java -jar openjml.jar -version
  echo "class Test { public static void m(int i) { /*@ assume i > 0; assert i >= 0; @*/ }}" > Test.java
  java -jar openjml.jar -esc -Werror Test.java
  if [ $? -eq 0 ]; then echo "OK"; else echo "FAILED"; fi
  echo "class Test { public static void m(int i) { /*@ assert i > 0; @*/ }}" > Test.java
  java -jar openjml.jar -esc -Werror Test.java
  if [ $? -ne 0 ]; then echo "OK"; else echo "FAILED"; fi
else echo "Download FAILED"
fi
cd ..
rm -rf temp-test

echo Download test complete
