#! /bin/bash

## Updates the OpenJML files at 
## https://sourceforge.net/projects/jmlspecs/files/OpenJML
## Note that these are just mirrors of (and a subset of)
## the files at jmlspecs.sourceforge.net

cd C:/cygwin/home/dcok/eprojects/OpenJML-UpdateSite
source web/setup

sftp davidcok,jmlspecs@web.sourceforge.net  << HERE
cd /home/frs/project/j/jm/jmlspecs/OpenJML
put web/README
put web/OpenJMLUserGuide.pdf
put web/*.gz openjml.tar.gz
exit
HERE


