#! /bin/bash

## This updates http://jmlspecs.sourceforge.net/
## and the associated update site with new files,
## but only uploading the most recent feature and plugins

cd C:/cygwin/home/dcok/eprojects/OpenJML-UpdateSite
source web/setup

sftp davidcok,jmlspecs@web.sourceforge.net  << HERE
cd htdocs
put web/index.html
put web/features.html
put web/book.css
put web/OpenJMLUserGuide.pdf
put web/OpenJML-projectSet.psf
put web/*.gz openjml.tar.gz
cd openjml-updatesite
put web/openjml-updatesite/index.html
put web/book.css
put site.xml
put content.jar
put artifacts.jar
put features/org.jmlspecs.openjml.OpenJMLFeature_${version}.jar features
put plugins/org.jmlspecs.*${version}.jar plugins

cd /home/frs/project/j/jm/jmlspecs/OpenJML
put web/README
put web/OpenJMLUserGuide.pdf
put web/*.gz openjml.tar.gz

exit
HERE



