#! /bin/bash

## This updates http://jmlspecs.sourceforge.net/
## just the web pages, not the actual release files on the Eclipse update site


cd `dirname $BASH_SOURCE`

./publish < ./webfiles
echo "Web files uploaded"

