#! /bin/bash

## This updates http://jmlspecs.sourceforge.net/
## and the associated update site with files,
## uploading all old files as well
## It also updates the JML project files.

cd `dirname $BASH_SOURCE`

cat webfiles allreleasefiles projectfiles | publish



